#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/opt/conda/envs/lfpy"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/opt/conda/envs/lfpy/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/work/examples/cells/x86_64/.libs/libnrnmech.so" "$@"
